### ISSUE TITLE
cap-library doesn't work on android

### ISSUE THREAD

**Issue by sschiavoni** [google/cap-library#14]
Original [issue 15](https://code.google.com/p/cap-library/issues/detail?id=15) created by shakusa@google.com on 2011-04-11T01:20:22.000Z:

wondering if you can help me to get your Cap library running on Android.

It seems to be having a problem resolving the schema factory:

No schema factory available for http://www.iana.org/assignments/media-types/application/relax-ng-compact-syntax

here is the Schema Factory Android page:

http://developer.android.com/reference/javax/xml/validation/SchemaFactory.html

Thanks and regards, Eric

I am seeing the following exception when attempting to parse a cap feed:

I/EventMonitor: (  717): &lt;?xml version='1.0' encoding='ISO-8859-1'?&gt; &lt;rss version='2.0'&gt; &lt;channel&gt;  &lt;title&gt;Hawaii Local Storm Reports 30 day archive&lt;/title&gt;  &lt;link&gt;http://www.prh.noaa.gov/hnl/pages/ls
r.php&lt;/link&gt;  &lt;description&gt;Local Storm Reports issued in the last 30 days from the National Weather Service Forecast Office in Honolulu, Hawaii.&lt;/description&gt;  &lt;language&gt;en-us&lt;/language&gt;  &lt;managingEdi
tor&gt;W-HFO.Webmaster@noaa.gov&lt;/managingEditor&gt;  &lt;webMaster&gt;W-HFO.Webmaster@noaa.gov&lt;/webMaster&gt;  &lt;lastBuildDate&gt;Sun,  3 Apr 2011 13:42:35 +0000&lt;/lastBuildDate&gt;  &lt;image&gt;   &lt;url&gt;http://weather.gov/images
/xml_logo.gif&lt;/url&gt;   &lt;title&gt;Hawaii Local Storm Reports 30 day archive&lt;/title&gt;   &lt;link&gt;http://www.prh.noaa.gov/hnl/pages/lsr.php&lt;/link&gt;  &lt;/image&gt;&lt;item&gt;&lt;title&gt; NON-TSTM WND D - CORRECTED PRELIMINARY LO
CAL STORM REPORT...CORRECTED&lt;/title&gt;&lt;link&gt;http://www.prh.noaa.gov/data/HFO/LSRHFO.1103172036&lt;/link&gt;&lt;description&gt;1018 AM     NON-TSTM WND DMG HONOLULU                21.31N 157.86W...&lt;/description&gt;&lt;pub
Date&gt;Thu, 17 Mar 2011 10:36:00 +1000&lt;/pubDate&gt;&lt;/item&gt;&lt;item&gt;&lt;title&gt; NON-TSTM WND D PRELIMINARY LOCAL STORM REPORT&lt;/title&gt;&lt;link&gt;http://www.prh.noaa.gov/data/HFO/LSRHFO.1103171819&lt;/link&gt;&lt;description&gt;0807
 AM     NON-TSTM WND DMG HONOLULU                21.31N 157.86W...&lt;/description&gt;&lt;pubDate&gt;Thu, 17 Mar 2011 8:17:00 +1000&lt;/pubDate&gt;&lt;/item&gt;&lt;item&gt;&lt;title&gt; TSTM WND DMG ,  HEAVY RAIN  PRELIMINARY LOCAL STOR
M REPORT&lt;/title&gt;&lt;link&gt;http://www.prh.noaa.gov/data/HFO/LSRHFO.1103041822&lt;/link&gt;&lt;description&gt;0415 AM     TSTM WND DMG     2 E WAIPAHU             21.39N 157.98W...&lt;/description&gt;&lt;pubDate&gt;Fri, 04 Mar 201
1 8:22:00 +1000&lt;/pubDate&gt;&lt;/item&gt;&lt;item&gt;&lt;title&gt; HEAVY RAIN  PRELIMINARY LOCAL STORM REPORT&lt;/title&gt;&lt;link&gt;http://www.prh.noaa.gov/data/HFO/LSRHFO.1103041642&lt;/link&gt;&lt;description&gt;0237 AM     HEAVY RAIN
 4 N KOLOA               21.96N 159.46W...&lt;/description&gt;&lt;pubDate&gt;Fri, 04 Mar 2011 2:42:00 +1000&lt;/pubDate&gt;&lt;/item&gt; &lt;/channel&gt; &lt;/rss&gt;
W/CapFeedParser(  717): No schema factory available for http://www.iana.org/assignments/media-types/application/relax-ng-compact-syntax
W/CapFeedParser(  717): java.lang.IllegalArgumentException: http://www.iana.org/assignments/media-types/application/relax-ng-compact-syntax
W/CapFeedParser(  717):         at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:192)
W/CapFeedParser(  717):         at com.google.publicalerts.cap.feed.CapFeedParser.loadRelaxNgSchema(CapFeedParser.java:85)
W/CapFeedParser(  717):         at com.google.publicalerts.cap.feed.CapFeedParser.&lt;clinit&gt;(CapFeedParser.java:78)
W/CapFeedParser(  717):         at net.cs76.projects.mobilealert.model.EventMonitor.getAlerts(EventMonitor.java:72)
W/CapFeedParser(  717):         at net.cs76.projects.mobilealert.WelcomeActivity$MonitorForEventsTask.doInBackground(WelcomeActivity.java:210)
W/CapFeedParser(  717):         at net.cs76.projects.mobilealert.WelcomeActivity$MonitorForEventsTask.doInBackground(WelcomeActivity.java:1)
W/CapFeedParser(  717):         at android.os.AsyncTask$2.call(AsyncTask.java:252)
W/CapFeedParser(  717):         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/CapFeedParser(  717):         at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/CapFeedParser(  717):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
W/CapFeedParser(  717):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
W/CapFeedParser(  717):         at java.lang.Thread.run(Thread.java:1020)
W/dalvikvm(  717): Exception Ljava/lang/IllegalArgumentException; thrown while initializing Lcom/google/publicalerts/cap/feed/CapFeedParser;
W/dalvikvm(  717): threadid=9: thread exiting with uncaught exception (group=0x40014760)
E/AndroidRuntime(  717): FATAL EXCEPTION: AsyncTask #&nbsp;1
E/AndroidRuntime(  717): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(  717):        at android.os.AsyncTask$3.done(AsyncTask.java:266)
E/AndroidRuntime(  717):        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
E/AndroidRuntime(  717):        at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
E/AndroidRuntime(  717):        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
E/AndroidRuntime(  717):        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime(  717):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1081)
E/AndroidRuntime(  717):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:574)
E/AndroidRuntime(  717):        at java.lang.Thread.run(Thread.java:1020)
E/AndroidRuntime(  717): Caused by: java.lang.ExceptionInInitializerError
E/AndroidRuntime(  717):        at net.cs76.projects.mobilealert.model.EventMonitor.getAlerts(EventMonitor.java:72)
E/AndroidRuntime(  717):        at net.cs76.projects.mobilealert.WelcomeActivity$MonitorForEventsTask.doInBackground(WelcomeActivity.java:210)
E/AndroidRuntime(  717):        at net.cs76.projects.mobilealert.WelcomeActivity$MonitorForEventsTask.doInBackground(WelcomeActivity.java:1)
E/AndroidRuntime(  717):        at android.os.AsyncTask$2.call(AsyncTask.java:252)
E/AndroidRuntime(  717):        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime(  717):        ... 4 more
E/AndroidRuntime(  717): Caused by: java.lang.IllegalArgumentException: http://www.w3.org/2001/XMLSchema
E/AndroidRuntime(  717):        at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:192)
E/AndroidRuntime(  717):        at com.google.publicalerts.cap.feed.CapFeedParser.loadXsd(CapFeedParser.java:103)
E/AndroidRuntime(  717):        at com.google.publicalerts.cap.feed.CapFeedParser.&lt;clinit&gt;(CapFeedParser.java:80)
E/AndroidRuntime(  717):        ... 9 more
W/ActivityManager(   72):   Force finishing activity net.cs76.projects.mobilealert/.WelcomeActivity
W/WindowManager(   72): Failure taking screenshot for (216x135) to layer 21010
I/TtsService(  454): Stopping

**Comment by AnthoSi** [comment]
I would like to use the library on android. Is there a tested way to make it working ?
Thanks,
Anthony
